DROP DATABASE IF EXISTS users_crud;
CREATE DATABASE users_crud;
\c users_crud
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS messages;

create table users (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(200),
	last_name VARCHAR(200),
	email VARCHAR(200),
	cc_number VARCHAR(200),
	gender VARCHAR(200),
	avatar_url VARCHAR(200)
);

CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  content VARCHAR(500),
  userID INT,
  FOREIGN KEY (userID) REFERENCES users(id)
);

insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Franciska', 'Best', 'fbest0@joomla.org', '201900518399173', 'Female', 'https://robohash.org/veltemporaquibusdam.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Roddie', 'Eighteen', 'reighteen1@webeden.co.uk', '5100134027545552', 'Male', 'https://robohash.org/quiquiconsequatur.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Zahara', 'Phillins', 'zphillins2@apache.org', '3589299137866472', 'Female', 'https://robohash.org/saepererumqui.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Matthiew', 'Vosper', 'mvosper3@earthlink.net', '3588094660394021', 'Male', 'https://robohash.org/evenietplaceatnulla.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Vin', 'Pinniger', 'vpinniger4@npr.org', '5602211589779101', 'Female', 'https://robohash.org/nullaaperiamvoluptatem.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Tommie', 'Iorillo', 'tiorillo5@hibu.com', '5533529575528271', 'Female', 'https://robohash.org/expeditatemporibusillo.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Shellysheldon', 'Ren', 'sren6@oracle.com', '3549900843380034', 'Male', 'https://robohash.org/nonvelvoluptas.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Cedric', 'Braghini', 'cbraghini7@cpanel.net', '3534660086139102', 'Male', 'https://robohash.org/estcupatevoluptatem.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Jonie', 'Farebrother', 'jfarebrother8@loc.gov', '3573027894335953', 'Female', 'https://robohash.org/laudantiumeummolestias.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Dagny', 'Kedwell', 'dkedwell9@typepad.com', '5602259441879700', 'Male', 'https://robohash.org/velfugiatiure.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Worth', 'Gehrts', 'wgehrtsa@google.com.br', '3579683382715637', 'Male', 'https://robohash.org/suntmaioressapiente.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Lorrayne', 'Zahor', 'lzahorb@archive.org', '4913392763383386', 'Female', 'https://robohash.org/ipsamvoluptatemvoluptas.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Alika', 'Capewell', 'acapewellc@google.cn', '376422780682227', 'Female', 'https://robohash.org/velitevenietest.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Francesco', 'Gealle', 'fgealled@seesaa.net', '30491743929320', 'Male', 'https://robohash.org/erroretaccusamus.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Reinold', 'Mityashev', 'rmityasheve@multiply.com', '3550916318721565', 'Male', 'https://robohash.org/dolorautcum.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Muire', 'Doni', 'mdonif@samsung.com', '3541581480748515', 'Female', 'https://robohash.org/voluptasinventorequia.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Isaak', 'Johann', 'ijohanng@so-net.ne.jp', '3528972163135996', 'Male', 'https://robohash.org/ipsamquiaenim.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Andrey', 'McNuff', 'amcnuffh@ted.com', '3557991206015084', 'Male', 'https://robohash.org/velitsunttenetur.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Pascale', 'Berlin', 'pberlini@shinystat.com', '5168417507024100', 'Male', 'https://robohash.org/insimiliqueeum.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Helaina', 'Roncelli', 'hroncellij@blogtalkradio.com', '201791854379295', 'Female', 'https://robohash.org/etsimiliqueomnis.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Sarina', 'Thickin', 'sthickink@time.com', '5147025770047900', 'Female', 'https://robohash.org/veladipisciet.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Othella', 'Fried', 'ofriedl@indiatimes.com', '4175004590724152', 'Female', 'https://robohash.org/utsedcorrupti.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Dalenna', 'Piercey', 'dpierceym@google.co.jp', '5100145943875287', 'Female', 'https://robohash.org/repudiandaequaeea.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Mersey', 'Donoghue', 'mdonoghuen@rambler.ru', '5002358063600471', 'Female', 'https://robohash.org/inventoreautarchitecto.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Hastings', 'Hoonahan', 'hhoonahano@google.com.hk', '5010123412829399', 'Male', 'https://robohash.org/etenimconsequatur.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Corey', 'Skade', 'cskadep@gov.uk', '6382229096293980', 'Female', 'https://robohash.org/ximeearum.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Myrta', 'Minette', 'mminetteq@mail.ru', '060452693596923069', 'Female', 'https://robohash.org/doloremquefugiatsimilique.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Marlena', 'Yeoman', 'myeomanr@shop-pro.jp', '3532700428136267', 'Female', 'https://robohash.org/consequaturmolestiaeneque.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Meryl', 'Schwerin', 'mschwerins@prnewswire.com', '4175000992841859', 'Male', 'https://robohash.org/temporeaharum.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Karla', 'Writtle', 'kwrittlet@ifeng.com', '6767349460047467505', 'Female', 'https://robohash.org/estutsunt.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Hieronymus', 'O''Kuddyhy', 'hokuddyhyu@ibm.com', '3547518201335929', 'Male', 'https://robohash.org/quasisuntenim.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Abram', 'O'' Molan', 'aomolanv@pen.io', '30253314918268', 'Male', 'https://robohash.org/laborumipsavoluptatem.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Petronella', 'Puncher', 'ppuncherw@privacy.gov.au', '5602236936206649', 'Female', 'https://robohash.org/quisitet.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Sapphira', 'Lesor', 'slesorx@over-blog.com', '3579960176860518', 'Female', 'https://robohash.org/autnumquamnon.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Neala', 'Guilford', 'nguilfordy@over-blog.com', '3552730970866693', 'Female', 'https://robohash.org/iustoinventoreaperiam.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Launce', 'Lyard', 'llyardz@wired.com', '3558685853274502', 'Male', 'https://robohash.org/consecteturquodolores.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Lory', 'Whitear', 'lwhitear10@apache.org', '374288385381214', 'Female', 'https://robohash.org/nonsintpossimus.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Jobina', 'Plover', 'jplover11@squarespace.com', '3531892769383441', 'Female', 'https://robohash.org/delectuspariaturlabore.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Jessy', 'Fernez', 'jfernez12@illinois.edu', '3545583429399018', 'Female', 'https://robohash.org/illumillocorporis.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Demetri', 'Mohammad', 'dmohammad13@behance.net', '3550822159557227', 'Male', 'https://robohash.org/omnisquiquia.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Stacia', 'Hunnam', 'shunnam14@joomla.org', '374283186133005', 'Female', 'https://robohash.org/autiureet.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Anny', 'Cockran', 'acockran15@e-recht24.de', '564182855870296284', 'Female', 'https://robohash.org/sintculpanisi.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Bone', 'Elkins', 'belkins16@shinystat.com', '4026698020512292', 'Male', 'https://robohash.org/eafacilisminima.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Rickey', 'Jefferson', 'rjefferson17@cmu.edu', '6763159104618614', 'Male', 'https://robohash.org/reiciendisdolorumnumquam.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Pierre', 'Borton', 'pborton18@list-manage.com', '3555621325548036', 'Male', 'https://robohash.org/voluptatemvoluptatemodi.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Lloyd', 'Kores', 'lkores19@mit.edu', '4041591179091294', 'Male', 'https://robohash.org/accusamusautporro.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Cyrus', 'Milesop', 'cmilesop1a@hc360.com', '3547252847816239', 'Male', 'https://robohash.org/consecteturbeataeaccusamus.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Heda', 'Jennick', 'hjennick1b@jugem.jp', '3556551435139195', 'Female', 'https://robohash.org/nonnihilmolestias.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Erminie', 'Doerling', 'edoerling1c@unicef.org', '201457589321115', 'Female', 'https://robohash.org/repudiandaeetvoluptatum.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Viva', 'Harbinson', 'vharbinson1d@t.co', '5038634418691946', 'Female', 'https://robohash.org/ducimustemporibusipsam.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Ulick', 'McVie', 'umcvie1e@taobao.com', '36309285825058', 'Male', 'https://robohash.org/autestet.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Bernardo', 'Bodleigh', 'bbodleigh1f@redcross.org', '5002354378468977', 'Male', 'https://robohash.org/velrepellatporro.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Tamara', 'Narramor', 'tnarramor1g@slate.com', '3564122913268649', 'Female', 'https://robohash.org/eaqueullamerror.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Karel', 'Mattussevich', 'kmattussevich1h@youku.com', '372301600142063', 'Male', 'https://robohash.org/undeutaccusamus.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Marne', 'Smalles', 'msmalles1i@pcworld.com', '502039974739761142', 'Female', 'https://robohash.org/molestiaesuntbeatae.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Ashlin', 'MacConnulty', 'amacconnulty1j@google.ca', '564182793861631799', 'Male', 'https://robohash.org/aliasullamut.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Gunilla', 'Langeley', 'glangeley1k@blogs.com', '4913771890197126', 'Female', 'https://robohash.org/doloremquedebitispraesentium.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Nehemiah', 'Shervil', 'nshervil1l@privacy.gov.au', '3570400851101010', 'Male', 'https://robohash.org/aperiamvoluptatemcumque.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Hyacinth', 'Colleck', 'hcolleck1m@rediff.com', '3574243715928657', 'Female', 'https://robohash.org/estsintnumquam.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Sly', 'Sangra', 'ssangra1n@chicagotribune.com', '3566298833649627', 'Male', 'https://robohash.org/ullamvoluptatesalias.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Caterina', 'Vickress', 'cvickress1o@fda.gov', '6759385335898917497', 'Female', 'https://robohash.org/rerumofficiavel.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Gennie', 'Marston', 'gmarston1p@independent.co.uk', '3533959750141464', 'Female', 'https://robohash.org/praesentiumfugaquia.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Hamnet', 'McKeown', 'hmckeown1q@xrea.com', '3565961820772006', 'Male', 'https://robohash.org/evenietexcepturiea.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Clemmie', 'Gladman', 'cgladman1r@delicious.com', '3555918207879053', 'Male', 'https://robohash.org/utsedet.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Daisi', 'Hebbron', 'dhebbron1s@360.cn', '3580577973892366', 'Female', 'https://robohash.org/dolornamminus.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Rosalie', 'Stollsteimer', 'rstollsteimer1t@usgs.gov', '3557993971613598', 'Female', 'https://robohash.org/impeditmaximeeveniet.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Mallissa', 'Parnell', 'mparnell1u@github.com', '3558285604435369', 'Female', 'https://robohash.org/repellatullamut.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Selestina', 'Adelberg', 'sadelberg1v@is.gd', '30595868448385', 'Female', 'https://robohash.org/faciliseumest.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Tannie', 'Neeson', 'tneeson1w@printfriendly.com', '6763502257822123473', 'Male', 'https://robohash.org/etrerumminus.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Elizabeth', 'Grangier', 'egrangier1x@mapy.cz', '201869602547478', 'Female', 'https://robohash.org/aliquirerum.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Tiff', 'Giuroni', 'tgiuroni1y@t-online.de', '3573529936098143', 'Female', 'https://robohash.org/estautnostrum.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Gerianne', 'Bessom', 'gbessom1z@pbs.org', '6334491250398331', 'Female', 'https://robohash.org/adipiscicumqueporro.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Neille', 'Points', 'npoints20@ocn.ne.jp', '3545798272891339', 'Female', 'https://robohash.org/solutamaioresrem.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Hew', 'Briance', 'hbriance21@t-online.de', '5124699739262763', 'Male', 'https://robohash.org/et.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Ruprecht', 'Ferebee', 'rferebee22@youku.com', '3534360391199939', 'Male', 'https://robohash.org/quoutdistinctio.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Jefferson', 'Jossel', 'jjossel23@multiply.com', '6397986359548706', 'Male', 'https://robohash.org/nobisdistinctioenim.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Scottie', 'Cordero', 'scordero24@google.co.jp', '3584081163567728', 'Male', 'https://robohash.org/namestsed.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Nettie', 'Geeraert', 'ngeeraert25@spotify.com', '3575575618388946', 'Female', 'https://robohash.org/voluptassequiesse.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Brewer', 'MacAdam', 'bmacadam26@buzzfeed.com', '201473880864216', 'Male', 'https://robohash.org/veritatisexercitationemea.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Bjorn', 'Sherland', 'bsherland27@photobucket.com', '4917182023819113', 'Male', 'https://robohash.org/sitoccaecatirerum.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Rickert', 'Routley', 'rroutley28@icio.us', '201910900631836', 'Male', 'https://robohash.org/voluptatemeosad.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Genna', 'Pavlenko', 'gpavlenko29@noaa.gov', '560222306927590121', 'Female', 'https://robohash.org/nonconsequaturculpa.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Mead', 'Mapother', 'mmapother2a@drupal.org', '3551224308443954', 'Male', 'https://robohash.org/esteasimilique.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Dorey', 'Van der Hoven', 'dvanderhoven2b@cnbc.com', '3584016868633755', 'Male', 'https://robohash.org/nemodignissimosautem.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Roxy', 'Querree', 'rquerree2c@stanford.edu', '5641828014191389', 'Female', 'https://robohash.org/reiciendisetest.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Lefty', 'Crampsy', 'lcrampsy2d@foxnews.com', '6396738975141858', 'Male', 'https://robohash.org/enimipsamest.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Benedetto', 'Tranfield', 'btranfield2e@virginia.edu', '3544178467138310', 'Male', 'https://robohash.org/aliqutaut.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Gaile', 'Collar', 'gcollar2f@yale.edu', '4017950866482101', 'Male', 'https://robohash.org/doloribusnobisillum.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Felicity', 'Phuprate', 'fphuprate2g@dyndns.org', '6762011089425096', 'Female', 'https://robohash.org/cumqueetnon.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Frank', 'Longden', 'flongden2h@mysql.com', '3581525873513359', 'Female', 'https://robohash.org/distinctioinctquam.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Standford', 'Andrewartha', 'sandrewartha2i@istockphoto.com', '3530767653410883', 'Male', 'https://robohash.org/necessitatibusdoloremqueullam.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Jemimah', 'Tremellier', 'jtremellier2j@miibeian.gov.cn', '3550910103979843', 'Female', 'https://robohash.org/eosconsecteturautem.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Noll', 'Newcomb', 'nnewcomb2k@oracle.com', '5610901518743570', 'Male', 'https://robohash.org/ametdolorumcorrupti.bmp?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Deboara', 'Dilliston', 'ddilliston2l@ted.com', '3569151434035216', 'Female', 'https://robohash.org/molestiaeeosculpa.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Margaretta', 'Soitoux', 'msoitoux2m@gmpg.org', '67596428632714137', 'Female', 'https://robohash.org/etexplicaborerum.jpg?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Carny', 'Lydster', 'clydster2n@tinypic.com', '30494170792732', 'Male', 'https://robohash.org/etiustonemo.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Fionnula', 'Leve', 'fleve2o@fema.gov', '201748958180698', 'Female', 'https://robohash.org/etquiasaepe.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Orville', 'Sparrowe', 'osparrowe2p@elpais.com', '3564752767731787', 'Male', 'https://robohash.org/quosundenihil.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ( 'Salomo', 'Seabourne', 'sseabourne2q@theguardian.com', '3557426944681475', 'Male', 'https://robohash.org/corporisnobissaepe.png?size=100x100&set=set1');
insert into users (first_name, last_name, email, cc_number, gender, avatar_url) values ('Bryant', 'McMullen', 'bmcmullen2r@rediff.com', '5425176768604799', 'Male', 'https://robohash.org/harumlaboriosamenim.png?size=100x100&set=set1');


insert into messages (content, userID) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 6);
insert into messages (content, userID) values ('Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 11);
insert into messages (content, userID) values ('Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 9);
insert into messages (content, userID) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 5);
insert into messages (content, userID) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 16);
insert into messages (content, userID) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 3);
insert into messages (content, userID) values ('Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 17);
insert into messages (content, userID) values ('Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 12);
insert into messages (content, userID) values ('Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 19);
insert into messages (content, userID) values ( 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 19);
insert into messages (content, userID) values ( 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 7);
insert into messages (content, userID) values ( 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 5);
insert into messages (content, userID) values ( 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 7);
insert into messages (content, userID) values ( 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 16);
insert into messages (content, userID) values ( 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 9);
insert into messages (content, userID) values ( 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 9);
insert into messages (content, userID) values ( 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 17);
insert into messages (content, userID) values ( 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 19);
insert into messages (content, userID) values ( 'Pellentesque at nulla. Suspendisse potenti.', 4);
insert into messages (content, userID) values ( 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 13);
insert into messages (content, userID) values ( 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 19);
insert into messages (content, userID) values ( 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 4);
insert into messages (content, userID) values ( 'In congue.', 8);
insert into messages (content, userID) values ( 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 13);
insert into messages (content, userID) values ( 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1);
insert into messages (content, userID) values ( 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 12);
insert into messages (content, userID) values ( 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 18);
insert into messages (content, userID) values ( 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 14);
insert into messages (content, userID) values ( 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 15);
insert into messages (content, userID) values ( 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 16);
insert into messages (content, userID) values ( 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 4);
insert into messages (content, userID) values ( 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 14);
insert into messages (content, userID) values ( 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 6);
insert into messages (content, userID) values ( 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 18);
insert into messages (content, userID) values ( 'Donec vitae nisi.', 13);
insert into messages (content, userID) values ( 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 17);
insert into messages (content, userID) values ( 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 15);
insert into messages (content, userID) values ( 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 20);
insert into messages (content, userID) values ( 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 6);
insert into messages (content, userID) values ( 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 13);
insert into messages (content, userID) values ( 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 17);
insert into messages (content, userID) values ( 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 4);
insert into messages (content, userID) values ( 'Proin risus.', 8);
insert into messages (content, userID) values ( 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 9);
insert into messages (content, userID) values ( 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 2);
insert into messages (content, userID) values ( 'Pellentesque ultrices mattis odio. Donec vitae nisi.', 15);
insert into messages (content, userID) values ( 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 19);
insert into messages (content, userID) values ( 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 16);
insert into messages (content, userID) values ( 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 17);
insert into messages (content, userID) values ( 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 15);